apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: bmdk1.azurecr.io/book_catalog:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://bookdb_lrqd_user:6614odHb7IpbXshtNjdc4weT8B4pgtk6@dpg-crcpujrv2p9s73ckop9g-a.oregon-postgres.render.com/bookdb_lrqd"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: bmdk1.azurecr.io/inventory_management:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: "postgresql://bookdb_lrqd_user:6614odHb7IpbXshtNjdc4weT8B4pgtk6@dpg-crcpujrv2p9s73ckop9g-a.oregon-postgres.render.com/bookdb_lrqd"

---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
